### PR TITLE
build: update to Angular13 and Eslint integration

### PR DESCRIPTION
**Pull request by sheikalthaf**
* Update the build to angular 13
* migrated from tslint to eslint

### CODE REVIEW

**Comment by sheikalthaf** [comment]
@llorenspujol need help in migrating the `tslint-rules` folder.

**Comment by llorenspujol** [comment]
@sheikalthaf I rebased your commits against `main`, since some code was added after this pull request. I also changed some things in the code, check it please, so we can verify it is all correct and  make sense.
After that, I removed the tslint rules in favor of a custom eslint plugin that can be found [here](https://github.com/katoid/eslint) (that recently made to unlock the upgrade to Angular 13).

Next steps for you @sheikalthaf :

1. Revise the final code and make some other changes if needed.
2. Make sure the final code is working in your local setup, so we verified it 2 times almost.
3. Squash ALL those commits into just one, so we keep story clean and you get the authory of the commit.

After those steps, I will merge the code 🎉 ! Thanks!

**Comment by sheikalthaf** [comment]
@llorenspujol Thanks for update. From my side all good. 

Will sqaush All commits into one

**Comment by sheikalthaf** [comment]
@llorenspujol Squashed all the commits. Hope it is good to go.

Thanks

**Comment by llorenspujol** [comment]
@sheikalthaf Seems thought that you used some other account for the commit, and I am not seeing you as a contributor in this repo. If you would like to be present as a contributor we can undo and re-merge, if not, it would be okay as it is. I am just pointing it out for you to know.

Thanks!

**Comment by sheikalthaf** [comment]
@llorenspujol I don't know how this happened. Need to check. It is possible to undo and re-merge the changes?

**Comment by llorenspujol** [comment]
@sheikalthaf I have undone the commit, you can make the PR again with the correct account

**Pull request merged**
