### PR TITLE
chore(grid): added prevent collision flag

### LINKED ISSUE #14: Feature: add preventCollision flag
In react-grid-layout there is preventCollision flag, which prevents layout from getting messed up in no compaction mode.
I would love to have this feature in there, I already made an implementation of it (it uses code from react-grid-layout which was already there).

### PR DESCRIPTION
**Pull request by jakubbialas**
Resolves #14

### CODE REVIEW

**Comment by llorenspujol** [comment]
Really nice work @jakubbialas , the code fits perfectly into the project, well done 👍 . 
I also agree that this functionality is really useful for no compaction layouts.

Before merging it, I want to comment one use case that seems a little bit weird for me. It also happens in react-grid-layout, but maybe we can do better. It happens when resizing, take this use case showed in the image:

image

The variable `leastY` gets the value from the layoutItem with id = 7 and the resized item gets just a height of 1, even its previous height may be 2 or 3. So, you want it bigger but it gets smaller.

I personally see 2 solutions:
- The minimum height of the resizing item when colliding is it's previous height, not less.
- Distinct between collided items and see if there is height space available, if so, just fit the height the maximum it can.

_Note that it happens the same with the width, the height is just used as the example_

Let me know what you think about this.

Thanks for contributing:)

**Comment by jakubbialas** [comment]
@llorenspujol thanks for you review, I implemented solution for shrinking issue, please give it a try.

**Comment by llorenspujol** [comment]
Merged into main branch! nice work! @jakubbialas . Expect a release during this week.

**Comment by llorenspujol** [comment]
preventCollision flag is present on version 0.2.0! 👏 

PD: I don't know why you don't show up on 'contributors' page of this repo... This time I tried rebasing with the github tool and maybe this has overwritten your commits or something... but is strange github doens't have some way of preserving commit authority even rebasing with it's own tool... 🤔 It makes a little bit angry since I want every contributor to show up on the repo... Just informing you about it, I will find why it happens to fix it for next contributions.

**Comment by jakubbialas** [comment]
Thanks for the release. No problem with the rebase, I know that I'm a contributor, and that is enough for me:)

**Pull request merged**
